
site_title: daniel baird dot com

url: https://danielbaird.com # or something
baseurl: / # or something

excerpt_separator: "\n"

# use category/title for permalinks
permalink: /:categories/:title/

# use disqus for comments, mainly copying jekyll-bootstrap
disqus:
    short_name: somethingorother

# use google for site stats, copying jekyll-bootstrap
google_analytics:
    tracking_id: 'UA-99244-1'


# # Build settings
# theme: minima

# plugins:
#   - jekyll-feed

markdown: kramdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

github: [metadata]
