
site_title: daniel baird dot com

url: http://danielbaird.com # or something
baseurl: / # or something

excerpt_separator: "\n"

# use category/title for permalinks
permalink: /:categories/:title/

# use disqus for comments, mainly copying jekyll-bootstrap
disqus:
    short_name: somethingorother

# use google for site stats, copying jekyll-bootstrap
google_analytics:
    tracking_id: 'UA-99244-1'