
site_title: daniel baird dot com
site_slogan: Blogging Is Stupid

url: http://danielbaird.github.com # or something
base_url: / # or something

# use category/title for permalinks
permalink: /:categories/:title/

# use disqus for comments, mainly copying jekyll-bootstrap
disqus:
    short_name: somethingorother

# use google for site stats, copying jekyll-bootstrap
google_analytics:
    tracking_id: 'UA-XXX-XX'